Repository Project-MONAI/MONAI, pull requests merged in 2022-10, with the labels that each got.

#5255 fix bug in retina detector
  monai/apps/detection/networks/retinanet_detector.py
Labels: bug

#5302 updates to Gaussian map for sliding window inference
  monai/data/utils.py
Labels: enhancement

#5292 fixes DiceCELoss for multichannel targets
  monai/data/box_utils.py
  monai/losses/dice.py
Labels: bug

#5297 SlidingWindowInferer: option to adaptively stitch in cpu memory for large images
  monai/inferers/inferer.py
Labels: enhancement

#5351 Enhancement for WarmupCosineSchedule to specify the beginning fraction of the linear warmup
  monai/optimizers/lr_scheduler.py
  tests/test_lr_scheduler.py
Labels: enhancement

#5355 MonaiAlgo: fix logging in multi-gpu training
  monai/fl/client/monai_algo.py
Labels: enhancement

#5350 A small update to to ensure ds_loss returns a const
  monai/losses/ds_loss.py
Labels: enhancement

#5364 update fl docs
  docs/source/fl.rst
  docs/source/modules.md
  docs/source/whatsnew_1_0.md
  monai/fl/client/client_algo.py
Labels: documentation
